### ISSUE TITLE
VCV2 Update?

### ISSUE THREAD

**Issue by trevormeier** [JustMog/Mog-VCV#6]
Will these be made available in the library for VCV2? According to [this discussion](https://community.vcvrack.com/t/plugins-that-are-questionable-whether-there-will-be-v2-updates/14364/405) they just need a version bump.

**Comment by JustMog** [comment]
not by me.
if curious, here's why:
https://aria.dog/barks/why-i-will-never-create-modules-for-vcv-rack-anymore/
aria is a friend, and i totally agree with her points here. i'm one of the people she mentions in "quitting".
the tl:dr is,
![image](https://user-images.githubusercontent.com/60553849/150597123-3f20a773-f4df-4877-b603-2048d3a38f7e.png)

**Comment by trevormeier** [comment]
Ah, ok - understood. Really sad to see the community split like this. I wish you well in whatever projects have your attention these days!

**Comment by trevormeier** [comment]
Would it be OK with you if someone were to take over this library? I'm not much of a programmer, and I'm not sure exactly the process but I can try and take on the task.

**Comment by AriaSalvatrice** [comment]
If Mog, myself, or a few other people no longer submit builds, it's not about the 2 hours it would take us to update the code with necessary fixes, and submit it. It's about no longer wanting to interact with Andrew Belt due to his rudeness, his habit of deleting anything critical of him, and VCV's code of conduct disallowing us from even discussing that fact.

Nothing, legally, bars you from laundering Mog's name, or that of others who have left, by submitting your own builds to VCV's app store.    
But the reason our code is Open-Source is to foster creativity and collaboration, not to make it easy for people to `make dist` on the code without providing further value.

To provide your own ports without further improvements:
- Forces us to provide support for our code within a host that, unlike [Cardinal](https://github.com/DISTRHO/Cardinal), we have chosen not to support.
- Forces us to remain present in spirit in the VCV community, when the VCV community has made it clear it doesn't want us around.

Rather than fix people's code, you should be fixing the VCV community such that it is respectful towards participants and inclusive towards women instead: if it were the case, we would be the first to be advocating for this platform.

**Comment by JustMog** [comment]
i suppose what i would say is, if you're asking for permission i can't rightly refuse, it's a cc0 license. but if you're asking for my blessing i can't in good conscience say yes. 
i don't bear anyone in the vcv community outside of the project lead any ill will, and that won't change if people miss my modules enough to fork them, but the idea of giving value or legitimacy to a for-profit company that treats its unpaid contributors with such disdain doesn't sit right with me.
as aria says, i also want to avoid a situation where i'm expected to provide further support for the code down the line, as i've washed my hands of the whole thing, and likewise a situation which gives the impression that i still give the vcv project my "backing" so to speak, when this is not the case.
it makes me sad that people who liked my modules might miss out through no fault of their own, but there it is. sorry i can't offer a more straightforward answer.

**Comment by trevormeier** [comment]
I fully respect your choice to no longer participate with VCV. I'm someone who tries to be kind and seek consent in everything I do. My asking the question of whether I can participate by helping with this code is not, in any way, asking anyone else to participate further. Nor am I condoning any poor behaviour. I can only do what I can do, and that is to try my best to act kindly and considerately wherever I find myself. I don't have any kind of standing or authority, nor am I a genius coder. Just a nerd musician reaching out to other helpful folks to see if I can help. 

@JustMog I feel like your answer is very straightforward and clear. I was asking for your blessing. That matters much more to me than what is legally possible. So I will leave it at that. I do miss this module, of course, but my desire for something wonderful and useful doesn't give me any right to have the thing. So - thanks for the contributions you made in the past. I wish you all the best.

**Comment by JustMog** [comment]
i have no objection to you (or anyone) compiling the modules for their personal use, that's fine. (if you weren't aware, modules can be added without going through the official library, which is what i'd prefer not to contribute to.)
appreciate you being so understanding, by the way.

**Comment by trevormeier** [comment]
I appreciate you being clear about your needs and preferences!

Thanks for the clarification on personal use.
